import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout';
import AnimatedText from '@/components/AnimatedText';
const inter = Inter({ subsets: ['latin'] })
import profilePic from "../../public/images/profile/mt-img-3-removebg-preview.png";
import profilePicOrig from "../../public/images/profile/my-img0-removebg.png";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import HireMe from '@/components/HireMe';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-black w-full min-h-screen'>
          <Layout className='pt-0'>
            <div className='flex items-center justify-between w-full'>
                <div className='w-1/2'>
                  <Image src={profilePic}  alt="Profile Image Of Aryan" className='w-full h-auto' />
                </div>
                <div className='w-1/2 flex flex-col items-center self-center'>
                  <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-4xl !text-left' />
                  <p>
                  As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.
                  </p>
                </div>
            </div>
          </Layout>
          <HireMe />
          <div className='absolute right-8 bottom-8 inline-block w-24'>
            <Image src={lightBulb} alt='Aryan Sharma' className='w-full h-auto'></Image>
          </div>
      </main>
    </>
  )
}
